CREATE_NAHDIONLINE_TABLE = "CREATE TABLE scrapped_data (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), age INT)"
INSERT_INTO_NAHDIONLINE_TABLE = "INSERT INTO scrapped_data (name, age) VALUES ('John', 25)"
SELECT_ALL_FROM_NAHDIONLINE_TABLE =  "SELECT * FROM scrapped_data"